spring:
  application:
    name: daily-photo
  datasource:
    url: jdbc:mysql://localhost:3306/daily_photo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true